### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by NicolasAndrehh** [getssh/personal-portfolio#11]
# Hi @getssh!
You did a good job with your project, but i think there are some things that can be improved
- When you open the modal in recent works in desktop version you can maybe decrease the size of the image for your project to be more like in the template
- In your js code you can agroup your code in functions for it to be more readable and easy to understand

**Comment by getssh** [comment]
Thank you for the feedback.
- I Reduced the size of the image
- Updated index.js document structure
