### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by cnualartc** [getssh/personal-portfolio#4]
Everything looks great! there are only minor things to be adjusted.

- the alignment of icons in the heading section, they should be aligned with the paragraph on top.
- the space underneath the icons has to be a little larger so that the text in the paragraph doesn't get lost with the background image.
- Another suggestion was to personalize the project by typing your name into the title

This is a summary of everyone's comments

**Comment by getssh** [comment]
Icons alignment and spacing got fixed.
Place holder name on header section changed to my name
